# Dev environment values
replicaCount: 1

image:
  repository: ghcr.io/o0akin0o/gitops-thesis-demo
  tag: 1ad034ed50728ca117a77afca92a89e937c2686a
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

environment: development
#   T e s t i n g   a u t o - s y n c   a f t e r   r e s t a r t 
 
 